name: elk-stack
services:
  setup:
    image: elasticsearch:8.19.21
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elastic\n"\
          "    dns:\n"\
          "      - elastic\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions";
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \+;
        find . -type f -exec chmod 640 \{\} \+;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://elastic:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elastic:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: [ "CMD-SHELL", "[ -f config/certs/elastic/elastic.crt ]" ]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      elk-stack-network:

  elastic:
    container_name: dict_elastic
    image: elasticsearch:8.19.21
    hostname: elastic
    restart: always
    ports:
      - "9200:9200"
    environment:
      node.name: "elastic"
      discovery.type: 'single-node'
      cluster.name: ${CLUSTER_NAME}
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "true"
      xpack.security.http.ssl.key: "certs/elastic/elastic.key"
      xpack.security.http.ssl.certificate: "certs/elastic/elastic.crt"
      xpack.security.http.ssl.certificate_authorities: "certs/ca/ca.crt"
      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.key: "certs/elastic/elastic.key"
      xpack.security.transport.ssl.certificate: "certs/elastic/elastic.crt"
      xpack.security.transport.ssl.certificate_authorities: "certs/ca/ca.crt"
      xpack.security.transport.ssl.verification_mode: "certificate"
      xpack.license.self_generated.type: "basic"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    mem_limit: 1g
    depends_on:
      setup:
        condition: service_healthy
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      elk-stack-network:

  kibana:
    container_name: dict_kibana
    image: kibana:8.19.21
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibana_data:/usr/share/kibana/data
    environment:
      SERVERNAME: "kibana"
      ELASTICSEARCH_HOSTS: "https://elastic:9200"
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "config/certs/ca/ca.crt"
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      XPACK_SECURITY_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
      XPACK_REPORTING_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
    mem_limit: 1g
    depends_on:
      elastic:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      elk-stack-network:

  logstash:
    container_name: logstash
    image: logstash:8.19.21
    networks:
      elk-stack-network:
    depends_on:
      elastic:
        condition: service_healthy
      kibana:
        condition: service_healthy
    ports:
      - "5200:5200"
    user: root
    volumes:
      - certs:/usr/share/logstash/certs
      - logstash_data:/usr/share/logstash/data
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      xpack.monitoring.enabled: "false"
      ELASTIC_USER: "elastic"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_HOSTS: "https://elastic:9200"
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      kibana:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ${NGINX_CONF_FILE_PATH}:/etc/nginx/nginx.conf
    networks:
      elk-stack-network:

  app:
    build: .
    image: elk-stack-app:latest
    container_name: elk_stack_app
    restart: always
    depends_on:
      kibana:
        condition: service_healthy
      elastic:
        condition: service_healthy
      setup:
        condition: service_healthy
    env_file:
      - ${APP_ENV_FILE_PATH}
    networks:
      elk-stack-network:




networks:
  elk-stack-network:
    driver: bridge
volumes:
  certs:
  elastic_data:
  kibana_data:
  logstash_data:
